### ISSUE TITLE
Enable borrowed Json and Form extractors

### ISSUE THREAD

**Issue by aliemjay** [HFQR/xitca-web#212]
https://github.com/HFQR/xitca-web/blob/119cfad2da7634055341f161a69c98251ec09508/http/src/util/service/handler.rs#L125

This requires FromRequest to have a mutable state to extract body and be able to reference it later.
Maybe change FromRequet to something similar to:
```rust
pub trait FromRequest<'a, Req>: Sized {
    type Type<'b>: FromRequest<'b, Req, Error = Self::Error>;

    type Stash: Default + 'static;
    type Error;
    type Future: Future<Output = Result<Self, Self::Error>>
    where
        Req: 'a;

    fn from_request(req: &'a Req, stash: &'a mut Self::Stash) -> Self::Future;
}
```

**Comment by fakeshadow** [comment]
I need to think about this.
The long term goal of the whole set api is to move to `async fn` in trait for a unified easy to write pattern. Even this means concurrent access have to hide behind some smart pointer.
Besides this FromRequest is in http layer for generic Request type so an additional type could mean a useless &mut () for low level use case.
Maybe we can change how it's exposed at web layer since it has it's own specific implementation of FromRquest which can be &(Req, Stash). The lack of &mut reference is unfortunate but it goes back to point 1. We can't have a concurrent `async fn from_request` take in &mut Stash anyway.

**Comment by fakeshadow** [comment]
#202
