### ISSUE TITLE
Upload release to crates.io?

### ISSUE THREAD

**Issue by SamuelMarks** [HFQR/xitca-web#749]
Using semantic versioning you can indicate that it's alpha :)

**Comment by fakeshadow** [comment]
Right now xitca-web depends on nightly rust compiler which means regardless what version naming is used it would "randomly" break on certain day(if you ever update your rust toolchain) due to possible bug/breaking change of nightly release. We really want to avoid that so as long as nightly is needed there will not be crate release. 

Luckily the nightly features needed will likely go in to stable in Rust 1.75. In other word at least partial crate release would happen at the end of this year.

**Comment by fakeshadow** [comment]
Future release can be tracked with https://github.com/HFQR/xitca-web/milestone/1 so I'm gonna go ahead and close this issue.
