### ISSUE TITLE
Nested Nested Apps don't work

### ISSUE THREAD

**Issue by Srlion** [HFQR/xitca-web#956]
Hey again!

Doing this doesn't work, just returns 404.
```rust
use xitca_web::{handler::handler_service, route::get, App};

fn main() {
     async fn test() -> &'static str {
		"hey"
	}

	let nested2 = App::new().at("/create", get(handler_service(test)));
	let nested = App::new().at("/v2", nested2);
	let app = App::new().at("/api", nested);

	app.serve().bind("localhost:8000")?.run().wait()
}
```
<br />

I know I can just send the app and directly add to it, but doing this way makes it way cleaner.
I feel like a good way to just make this work by just collecting all routes and prepending the main route to them, eg.
```
/api
  /v2
    /create
    /delete

"/v2" gets prepended to "/create" and "/delete".
"/api" gets prepended to "/v2/create" and "/v2/delete".
```
I haven't checked the router code to determine if this is more efficient or not, but I suppose it is.

**Comment by fakeshadow** [comment]
Thanks for the issue. This is a limitation and bug in the router where it will lose context of router path generating once it's nested. I would look into it.

**Comment by fakeshadow** [comment]
With https://github.com/HFQR/xitca-web/pull/957 this issue is resolved.

**Comment by fakeshadow** [comment]
That said do note that xitca routing nested router in linear manner. which means for the example use in this issue there will be 3 three routers generated:
1. `/api/*`
2. `/api/v2/*`
3. `/api/v2/create`

A request path must be matched against every one in top down order to find the according route service. Apparently this is less efficient than using single router. 

This is done this way for simpler router design by keeping it consistent with `matchit`. If more efficient nesting routers is desired I would suggest to open issue to said crate. I'm also open to idea of using other router crates that can achieve the same goal.

**Comment by Srlion** [comment]
Do you mean that you have to do 3 `match_it.at` calls to reach it?

**Comment by fakeshadow** [comment]
> Do you mean that you have to do 3 `match_it.at` calls to reach it?

yes that's correct.

**Comment by Srlion** [comment]
@fakeshadow any reason on why not make it simple by collecting added routes and adding it directly to the main ``matchit`` router? I was playing with making a http framework on top of hyper and had these two functions that collect all routes to main router, here is what I mean:

```rust
#[inline]
pub fn generate(self) -> Result<MatchRouter<F>, matchit::InsertError> {
	let mut match_router = MatchRouter::new();

	let handlers: Vec<(Option<Method>, Handler<F>)> = self.handlers;
	match_router.insert(&self.path, handlers)?;

	Self::child_routers(self.routers, &mut match_router)?;
	Ok(match_router)
}

#[inline]
fn child_routers(
	routers: Vec<Router<F>>,
	match_router: &mut MatchRouter<F>,
) -> Result<(), matchit::InsertError> {
	for router in routers {
		let handlers: Vec<(Option<Method>, Handler<F>)> = router.handlers;

		match_router.insert(router.path, boxed_router)?;
		Self::child_routers(router.routers, match_router)?;
	}
	Ok(())
}
```
I believe this significantly simplifies the process and aligns with the intended use of matchit.

**Comment by fakeshadow** [comment]
Because xitca is a composable framework where a route can be one of many possible types. For example:
```rust
App::new()
    .at("/1", fn_service(..))
    .at("/2", get(fn_service(..)))
    .at("/3", Redirect::see_other("/1"))
    .at("/4", Router::new())
    .at("/5", Router::new().ecnlosed(Middleware))
```

Everyone of them would produce different types of route and the only way to store them in a single router is to cast them into trait objects where the types are erased so there is no way to know what route is a nest router.

It's possible to add new trait bound for additional logic to handle routes differently based on their types which is what xitca is already doing where `PathGen` and `RouteGen` traits are used. That being said this approach also coming with one down side.
below is a router with middleware:
```rust
let mut router = Router::new().ecnlosed(Middleware));
```
In order to transform it to a router you have to do this:
```rust
router = router.drain().map(|(k, v)| (k, v.enclosed(Middleware)).collect();
```
Which means you have to construct a separate middleware for every route in the router instead of only construct one around the router itself. This can result in exponential memory bloating when multiple routes are stored in a router with multiple middlewares around the router. And one of the most important design choice of xitca is to be memory efficient when possible which means we always choose some extra cpu cycle compared to more allocated memory.

**Comment by Srlion** [comment]
This sums it up! Thanks for the clarification, and thank you for this great framework!

**Comment by fakeshadow** [comment]
A new release has been made to address the issue. And the release has also "fixed" the performance issue of multi layer of nesting.
With the new release multi layer of nesting routers will only pay for extra request path string slicing and boxed object of indirection pointer look up.
